In [1]:
import numpy as np

In [2]:
arr1 = np.random.rand(2, 3)
arr2 = np.random.rand(3, 6)

In [4]:
# magic function
arr1.__matmul__(arr2)

array([[0.73755219, 1.19013533, 0.15363159, 0.56697303, 1.2658308 ,
        0.75824718],
       [0.61716168, 1.15337402, 0.35166552, 0.6554803 , 1.14435584,
        0.7845949 ]])

In [3]:
arr1 @ arr2

array([[0.73755219, 1.19013533, 0.15363159, 0.56697303, 1.2658308 ,
        0.75824718],
       [0.61716168, 1.15337402, 0.35166552, 0.6554803 , 1.14435584,
        0.7845949 ]])

In [5]:
np.matmul(arr1, arr2)

array([[0.73755219, 1.19013533, 0.15363159, 0.56697303, 1.2658308 ,
        0.75824718],
       [0.61716168, 1.15337402, 0.35166552, 0.6554803 , 1.14435584,
        0.7845949 ]])

In [6]:
np.dot(arr1, arr2)

array([[0.73755219, 1.19013533, 0.15363159, 0.56697303, 1.2658308 ,
        0.75824718],
       [0.61716168, 1.15337402, 0.35166552, 0.6554803 , 1.14435584,
        0.7845949 ]])

In [7]:
arr3 = np.random.rand(2, 3, 4)
arr4 = np.random.rand(2, 4, 6)

In [12]:
arr3

array([[[0.09041647, 0.78911659, 0.66852535, 0.51938844],
        [0.53559945, 0.20459015, 0.55626548, 0.8154984 ],
        [0.57366771, 0.17271926, 0.16136014, 0.48268263]],

       [[0.18997029, 0.61822041, 0.40933541, 0.89758551],
        [0.62748851, 0.07472826, 0.80399643, 0.76244996],
        [0.90092496, 0.67360035, 0.39614495, 0.78568992]]])

In [13]:
arr4

array([[[0.1246972 , 0.55141175, 0.60222668, 0.85607466, 0.09286037,
         0.23843887],
        [0.96256583, 0.26177104, 0.81708766, 0.75109222, 0.92757474,
         0.6734123 ],
        [0.85493362, 0.8247518 , 0.68511819, 0.56443375, 0.54279092,
         0.06029864],
        [0.45220444, 0.34572748, 0.29980881, 0.38273118, 0.04066215,
         0.06866358]],

       [[0.40787647, 0.02018166, 0.1473556 , 0.17437731, 0.48237538,
         0.04345277],
        [0.73789491, 0.16917539, 0.97423769, 0.69124446, 0.4376764 ,
         0.01656843],
        [0.24946742, 0.64874407, 0.50150707, 0.28541178, 0.60260114,
         0.04367244],
        [0.17339231, 0.42782615, 0.1271457 , 0.36590027, 0.93588772,
         0.98514864]]])

In [9]:
np.matmul(arr3, arr4).shape

(2, 3, 6)

In [10]:
np.dot(arr3, arr4).shape

(2, 3, 2, 6)

In [11]:
np.dot(arr3, arr4)

array([[[[1.5772659 , 0.98735892, 1.31296475, 1.246227  , 1.12434966,
          0.62893386],
         [0.87599712, 0.79123368, 1.1834187 , 0.94208844, 1.27793579,
          0.55787422]],

        [[1.1080613 , 1.08961277, 1.11532158, 1.23827086, 0.57460439,
          0.35501834],
         [0.64959571, 0.75518638, 0.6609012 , 0.69197401, 1.44632542,
          0.85434363]],

        [[0.59401185, 0.66149873, 0.74186806, 0.89664529, 0.32069275,
          0.29596847],
         [0.48538178, 0.3519831 , 0.39509704, 0.44209366, 0.90129088,
          0.51035027]]],


       [[[1.37461336, 0.91450414, 1.16909262, 1.20154596, 0.84976764,
          0.54792733],
         [0.79141637, 0.75798607, 0.94969555, 0.90572387, 1.44892271,
          0.9206295 ]],

        [[1.18232377, 1.29226364, 1.21837167, 1.33892092, 0.59498968,
          0.30077302],
         [0.64385328, 0.87308989, 0.66541917, 0.66952596, 1.53344853,
          0.81474327]],

        [[1.45469761, 1.27146553, 1.59991446, 1.80150063, 