In [1]:
import numpy as np

np.__version__

'1.22.4'

In [2]:
arr1 = np.array([1, 2, 3]) # 1D array
arr2 = np.array([4, 5, 6]) # 1D array

In [6]:
arr1.shape

(3,)

In [9]:
concat_arr = np.concatenate([arr1, arr2], axis=0)
concat_arr

array([1, 2, 3, 4, 5, 6])

In [11]:
concat_arr[0]

1

In [13]:
concat_arr.shape

(6,)

In [10]:
stack_arr = np.stack([arr1, arr2], axis=0)
stack_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
stack_arr[0]

array([1, 2, 3])

In [14]:
stack_arr.shape

(2, 3)

### 2D arrayler

In [15]:
arr1 = np.random.randint(low=0, high=5, size=(3,3))
arr1

array([[3, 3, 4],
       [1, 0, 4],
       [3, 3, 1]])

In [16]:
arr2 = np.random.randint(low=0, high=5, size=(3,3))
arr2

array([[4, 0, 3],
       [0, 2, 3],
       [1, 4, 4]])

In [21]:
np.concatenate([arr1, arr2], axis=0) # (6, 3)

array([[3, 3, 4],
       [1, 0, 4],
       [3, 3, 1],
       [4, 0, 3],
       [0, 2, 3],
       [1, 4, 4]])

In [22]:
np.concatenate([arr1, arr2], axis=1) # (3, 6)

array([[3, 3, 4, 4, 0, 3],
       [1, 0, 4, 0, 2, 3],
       [3, 3, 1, 1, 4, 4]])

In [25]:
np.stack([arr1, arr2], axis=0) # (2, 3, 3)

array([[[3, 3, 4],
        [1, 0, 4],
        [3, 3, 1]],

       [[4, 0, 3],
        [0, 2, 3],
        [1, 4, 4]]])

In [26]:
np.stack([arr1, arr2], axis=1) # (3, 2, 3)

array([[[3, 3, 4],
        [4, 0, 3]],

       [[1, 0, 4],
        [0, 2, 3]],

       [[3, 3, 1],
        [1, 4, 4]]])

In [29]:
np.stack([arr1, arr2], axis=0)[0]

array([[3, 3, 4],
       [1, 0, 4],
       [3, 3, 1]])