In [1]:
import numpy as np
np.__version__

'1.22.4'

In [4]:
[i for i in range(0, 10, 2)]

[0, 2, 4, 6, 8]

In [10]:
arr = np.array([i for i in range(20, 60, 2)])
arr

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58])

In [11]:
arr[[3, 9]]

array([26, 38])

In [14]:
arr = arr.reshape(4, 5)
arr

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [21]:
arr[[1, -1]]

array([[30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58]])

In [22]:
arr[[1, -1], [0, 2]]

array([30, 54])

In [23]:
row_indices = np.array([1, -1])
column_indices = np.array([0, 2])

row_indices, row_indices.shape

(array([ 1, -1]), (2,))

In [27]:
row_indices_expanded = np.expand_dims(row_indices, axis=-1)
column_indices_expanded = np.expand_dims(column_indices, axis=-1)

In [31]:
arr

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [36]:
row_indices

array([ 1, -1])

In [33]:
column_indices_expanded

array([[0],
       [2]])

In [38]:
arr[row_indices, column_indices]

array([30, 54])

In [39]:
arr[row_indices, column_indices_expanded]

array([[30, 50],
       [34, 54]])

In [40]:
arr[row_indices_expanded, column_indices]

array([[30, 34],
       [50, 54]])

In [41]:
arr[row_indices_expanded, column_indices_expanded]

array([[30],
       [54]])