In [1]:
import numpy as np
np.__version__

'1.22.4'

In [4]:
exam_scores = np.random.uniform(low = 0, high = 101, size = (20, 4))
exam_scores = exam_scores.astype(np.int32)
exam_scores

array([[82, 84, 75, 66],
       [ 2, 86, 41, 45],
       [33, 49, 89, 30],
       [13, 51, 53, 56],
       [18, 72, 56, 75],
       [13,  9, 10, 67],
       [52, 98, 78, 83],
       [ 1,  0, 96, 83],
       [89, 55, 86, 92],
       [ 7, 66, 70,  1],
       [23, 21, 85, 63],
       [ 2, 76, 97, 63],
       [94, 34, 16, 92],
       [61, 55, 98,  5],
       [72, 38, 35,  6],
       [92, 44, 64, 52],
       [96, 24, 34,  3],
       [16, 75, 76, 49],
       [86, 39, 17, 14],
       [96, 24, 45, 33]], dtype=int32)

In [6]:
exam_scores_normalized = exam_scores / 100
exam_scores_normalized

array([[0.82, 0.84, 0.75, 0.66],
       [0.02, 0.86, 0.41, 0.45],
       [0.33, 0.49, 0.89, 0.3 ],
       [0.13, 0.51, 0.53, 0.56],
       [0.18, 0.72, 0.56, 0.75],
       [0.13, 0.09, 0.1 , 0.67],
       [0.52, 0.98, 0.78, 0.83],
       [0.01, 0.  , 0.96, 0.83],
       [0.89, 0.55, 0.86, 0.92],
       [0.07, 0.66, 0.7 , 0.01],
       [0.23, 0.21, 0.85, 0.63],
       [0.02, 0.76, 0.97, 0.63],
       [0.94, 0.34, 0.16, 0.92],
       [0.61, 0.55, 0.98, 0.05],
       [0.72, 0.38, 0.35, 0.06],
       [0.92, 0.44, 0.64, 0.52],
       [0.96, 0.24, 0.34, 0.03],
       [0.16, 0.75, 0.76, 0.49],
       [0.86, 0.39, 0.17, 0.14],
       [0.96, 0.24, 0.45, 0.33]])

In [23]:
exam_scores_normalized.shape

(20, 4)

In [17]:
mean_exam_scores = np.mean(exam_scores_normalized, axis=0)
mean_exam_scores = np.around(mean_exam_scores, decimals=2)
mean_exam_scores

array([0.47, 0.5 , 0.61, 0.49])

In [22]:
np.array([0.82, 0.84, 0.75, 0.66]) - np.array([0.47, 0.5 , 0.61, 0.49])

array([0.35, 0.34, 0.14, 0.17])

In [18]:
exam_scores_normalized.shape

(20, 4)

In [19]:
mean_exam_scores.shape

(4,)

In [20]:
exam_scores_normalized - mean_exam_scores

array([[ 0.35,  0.34,  0.14,  0.17],
       [-0.45,  0.36, -0.2 , -0.04],
       [-0.14, -0.01,  0.28, -0.19],
       [-0.34,  0.01, -0.08,  0.07],
       [-0.29,  0.22, -0.05,  0.26],
       [-0.34, -0.41, -0.51,  0.18],
       [ 0.05,  0.48,  0.17,  0.34],
       [-0.46, -0.5 ,  0.35,  0.34],
       [ 0.42,  0.05,  0.25,  0.43],
       [-0.4 ,  0.16,  0.09, -0.48],
       [-0.24, -0.29,  0.24,  0.14],
       [-0.45,  0.26,  0.36,  0.14],
       [ 0.47, -0.16, -0.45,  0.43],
       [ 0.14,  0.05,  0.37, -0.44],
       [ 0.25, -0.12, -0.26, -0.43],
       [ 0.45, -0.06,  0.03,  0.03],
       [ 0.49, -0.26, -0.27, -0.46],
       [-0.31,  0.25,  0.15,  0.  ],
       [ 0.39, -0.11, -0.44, -0.35],
       [ 0.49, -0.26, -0.16, -0.16]])