# NumPy Giriş (Numerical Python)

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np # alias
np.__version__

'1.22.4'

## Array Oluşturmak

In [4]:
x = np.array([1, 2, 3, 4]) # 1D --> vektor
x

array([1, 2, 3, 4])

In [5]:
np.shape(x)

(4,)

In [7]:
x_2d = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]])
x_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.shape(x_2d)

(2, 4)

In [9]:
x_3d = np.array([[[1, 2, 3, 4], 
                 [5, 6, 7, 8]]])
x_3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [10]:
np.shape(x_3d)

(1, 2, 4)

In [11]:
x_2d.shape

(2, 4)

In [13]:
np.shape([1, 2, 3, 4])

(4,)