In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
arr = np.random.rand(3, 4)
arr

array([[0.91282031, 0.58536259, 0.10725436, 0.76871764],
       [0.73046347, 0.50907044, 0.00857226, 0.90675597],
       [0.99478384, 0.22667138, 0.74479724, 0.86040166]])

In [6]:
arr.shape

(3, 4)

In [12]:
arr.max(axis=0)

array([0.99478384, 0.58536259, 0.74479724, 0.90675597])

In [9]:
arr.flatten()

array([0.91282031, 0.58536259, 0.10725436, 0.76871764, 0.73046347,
       0.50907044, 0.00857226, 0.90675597, 0.99478384, 0.22667138,
       0.74479724, 0.86040166])

In [11]:
arr

array([[0.91282031, 0.58536259, 0.10725436, 0.76871764],
       [0.73046347, 0.50907044, 0.00857226, 0.90675597],
       [0.99478384, 0.22667138, 0.74479724, 0.86040166]])

In [13]:
np.argmin(arr, axis=0)

array([1, 2, 1, 0])

In [14]:
# İleri seviye yorumlama konusu - temel ML bilgisi ile
# daha iyi anlaşılabilir.
class_probs = np.array([[0.8, 0.2], [0.1, 0.9]])
class_probs

array([[0.8, 0.2],
       [0.1, 0.9]])

In [15]:
np.argmax(class_probs, axis=1)

array([0, 1])