In [1]:
import numpy as np

np.__version__

'1.22.4'

In [2]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
# View oluşturma
arr2 = arr[1:] # basic indexing - view döndürür
arr2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
arr[1, 1] = 12

In [8]:
arr2

array([[ 4, 12,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
arr

array([[ 0,  1,  2,  3],
       [ 4, 12,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
# Copy oluşturma

arr3 = arr[[1, 2]] # advanced indexing - copy döndürür
arr3

array([[ 4, 12,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
arr[1, 2] = 1500

In [15]:
arr3

array([[ 4, 12,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
arr2.base

array([   0,    1,    2,    3,    4,   12, 1500,    7,    8,    9,   10,
         11,   12,   13,   14,   15])

In [21]:
print(arr3.base is None)

True
