In [1]:
import numpy as np
np.__version__

'1.22.4'

View - Shallow Copy

Copy - Deep Copy

In [2]:
arr = np.array([1, 2, 3])

In [3]:
id(arr)

139856960212784

In [4]:
arr2 = np.array([1, 2, 3])

In [5]:
id(arr2)

139856957488656

In [6]:
arr3 = arr

In [7]:
id(arr3)

139856960212784

In [8]:
arr.shape

(3,)

In [9]:
arr = np.expand_dims(arr, axis=-1)
arr

array([[1],
       [2],
       [3]])

In [11]:
id(arr3)

139856960212784

In [12]:
id(arr)

139856956477712

In [13]:
arr3 = arr # no copy

In [15]:
arr3[1] = 10

In [16]:
arr

array([[ 1],
       [10],
       [ 3]])

In [18]:
arr3.base

array([ 1, 10,  3])

In [19]:
arr4 = np.copy(arr) # deep copy

In [20]:
arr4.base

In [22]:
arr4[2] = 1500

In [23]:
arr

array([[ 1],
       [10],
       [ 3]])

In [25]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',