In [1]:
import numpy as np

np.__version__

'1.22.4'

In [3]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [5]:
determinant_arr = np.linalg.det(arr)
determinant_arr

-2.0000000000000004

In [ ]:
# 2x2 (kare satır ve sütun sayısı eşit) matriste determinant hesabı
# 1(a) 2(b)
# 3(c) 4(d) --> a*d - b*c
# 1*4 - 2*3 = -2

In [9]:
arr2 = np.array([[1, 2, 5], [3, 4, 5]]) # shape (2, 3)
arr2

array([[1, 2, 5],
       [3, 4, 5]])

In [10]:
# kare matris olmadığı için çalışmaz
np.linalg.det(arr2)

LinAlgError: ignored

In [11]:
arr3 = np.array([[1, 2, 5], [3, 4, 5], [7, 8, 12]]) # shape (3, 3)
arr3

array([[ 1,  2,  5],
       [ 3,  4,  5],
       [ 7,  8, 12]])

In [12]:
np.linalg.det(arr3)

-14.000000000000004

In [ ]:
# Matrisin tersi 
# A matrisimiz var, bunun tersi B olsun.
# A * B = Birim Matris

In [22]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [ ]:
# arr * arr_ters = I

In [21]:
np.around(arr @ np.linalg.inv(arr), 3)

array([[1., 0.],
       [0., 1.]])

In [23]:
arr5 = np.array([[1, 2], [2, 4]])
np.linalg.det(arr5)

0.0

In [24]:
np.around(arr5 @ np.linalg.inv(arr5), 3)

LinAlgError: ignored