In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [3]:
arr1 + arr2

array([5, 7, 9])

In [5]:
arr1.shape, arr2.shape

((3,), (3,))

In [6]:
arr1 + 100 # shape ()

array([101, 102, 103])

In [7]:
arr3 = np.array([7, 8, 9]) # (3,)

arr4 = np.array([[4, 5, 6], 
                 [10, 11, 12]]) # (2, 3)

In [9]:
arr4.shape

(2, 3)

In [10]:
arr3 + arr4

array([[11, 13, 15],
       [17, 19, 21]])

In [11]:
arr5 = np.array([7, 8]) # (2,)

arr5 + arr4

ValueError: ignored