In [1]:
import numpy as np

np.__version__

'1.22.4'

In [2]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

In [3]:
l1 + l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
l_toplam = []
for l1_item, l2_item in zip(l1, l2):
    l_toplam.append(l1_item + l2_item)

In [5]:
l_toplam

[6, 8, 10, 12]

In [9]:
l_toplam = np.add(l1, l2)
l_toplam

array([ 6,  8, 10, 12])

In [10]:
np.add.reduce(l_toplam)

36

In [11]:
np.sum(l_toplam)

36

In [12]:
arr1 = np.arange(0, 36).reshape(4, 9)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [18]:
arr1.shape

(4, 9)

In [19]:
np.add.reduce(arr1, 1)

array([ 36, 117, 198, 279])

In [21]:
np.sum(arr1)

630

In [22]:
np.add.reduce(arr1, None)

630