In [1]:
import numpy as np

np.__version__

'1.22.4'

1) Bir liste oluşturup onu daha sonra numpy arrayine çevirin.

In [3]:
l1 = [1, 2, 4, 6]
l1 = np.array(l1)
l1

array([1, 2, 4, 6])

2) 10'dan başlayıp 19'a kadar olan sayılardan 3x3 bir matris oluşturun.

In [5]:
np.arange(10, 19).reshape(3,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
np.array([i for i in range(10, 19)]).reshape(3, 3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
np.reshape(np.arange(10, 19), (3, 3))

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

3) 15 tane 1'den oluşan bir array oluşturup sondan ikinci elemanı 12 olacak şekilde değiştirin.

In [9]:
arr = np.ones(15)
arr[-2] = 12

arr

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
       12.,  1.])

4) Bir array oluşturup elemanların sırasını tersine çevirin.

In [12]:
arr[::-1]

array([ 1., 12.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

In [15]:
rand_arr = np.random.rand(2, 2)
rand_arr

array([[0.41156707, 0.49676839],
       [0.16093928, 0.13645566]])

In [16]:
rand_arr[::-1]

array([[0.16093928, 0.13645566],
       [0.41156707, 0.49676839]])

5) Float değerlerden oluşan random bir arrayi integer tipine cast edin.

In [18]:
arr = np.random.uniform(low=1, high=5, size = (10, 2)) * 50
arr 

array([[137.73849748, 147.00845593],
       [218.09318642,  70.35777461],
       [211.46746437, 165.17478221],
       [180.73201987, 113.10650868],
       [224.86892887,  56.58565486],
       [198.77988975,  72.33526428],
       [116.22143005, 249.26539935],
       [119.11748295, 121.97761686],
       [225.36260214,  86.23209866],
       [ 68.36014427, 122.28145724]])

In [19]:
arr = arr.astype(np.int32)
arr

array([[137, 147],
       [218,  70],
       [211, 165],
       [180, 113],
       [224,  56],
       [198,  72],
       [116, 249],
       [119, 121],
       [225,  86],
       [ 68, 122]], dtype=int32)

6) 7x7 bir array oluşturup içinde bulunan 5x5'lik kısımların değerlerini 2 olacak şekilde değiştirin.

In [27]:
arr = (np.random.uniform(low=1, high=5, size = (7, 7)) * 50).astype(np.int32)
arr 

array([[107,  55, 133, 201,  89, 233,  95],
       [170, 142, 207, 213, 228, 242,  80],
       [121, 225, 246,  74,  84,  53, 244],
       [150, 118, 178, 201, 221, 154, 113],
       [ 73, 156, 135, 225, 143, 186, 152],
       [176,  67, 239, 185, 224, 193, 196],
       [214, 102, 150, 205, 238, 156, 214]], dtype=int32)

In [37]:
arr[1:-1, 1:-1] = 2
arr

array([[107,  55, 133, 201,  89, 233,  95],
       [170,   2,   2,   2,   2,   2,  80],
       [121,   2,   2,   2,   2,   2, 244],
       [150,   2,   2,   2,   2,   2, 113],
       [ 73,   2,   2,   2,   2,   2, 152],
       [176,   2,   2,   2,   2,   2, 196],
       [214, 102, 150, 205, 238, 156, 214]], dtype=int32)

Bonus) Bir arrayin çevresini istediğiniz bir değerle kaplayın.

In [46]:
np.pad(arr, pad_width = 2, constant_values=1234)

array([[1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234],
       [1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234],
       [1234, 1234,  107,   55,  133,  201,   89,  233,   95, 1234, 1234],
       [1234, 1234,  170,    2,    2,    2,    2,    2,   80, 1234, 1234],
       [1234, 1234,  121,    2,    2,    2,    2,    2,  244, 1234, 1234],
       [1234, 1234,  150,    2,    2,    2,    2,    2,  113, 1234, 1234],
       [1234, 1234,   73,    2,    2,    2,    2,    2,  152, 1234, 1234],
       [1234, 1234,  176,    2,    2,    2,    2,    2,  196, 1234, 1234],
       [1234, 1234,  214,  102,  150,  205,  238,  156,  214, 1234, 1234],
       [1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234],
       [1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234, 1234]],
      dtype=int32)

7) 2x2 bir matris oluşturup sonradan bir sütun ekleyin. Yeni shape (2, 3) olmalı.

In [47]:
arr = np.array([
    [1, 2],
    [3, 4]
])
arr

array([[1, 2],
       [3, 4]])

In [53]:
np.array([[5, 6]]).shape

(1, 2)

In [54]:
np.array([[5, 6]]).T.shape

(2, 1)

In [52]:
np.concatenate([arr, np.array([[5, 6]]).T], axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [58]:
arr = np.concatenate([arr, np.array([[5], [6]])], axis=1)
arr

array([[1, 2, 5],
       [3, 4, 6]])

In [56]:
np.array([[5], [6]]).shape

(2, 1)

8) Bir matris oluşturup toplam eleman sayısını bulun.

In [59]:
len(arr)

2

In [60]:
arr.size

6

In [62]:
len(arr.flatten())

6

9) İki matris oluşturup ortak elemanları bulun.

In [63]:
arr

array([[1, 2, 5],
       [3, 4, 6]])

In [64]:
arr2 = np.array([[1, 24, 5],
                 [3, 48, 61]])
arr2

array([[ 1, 24,  5],
       [ 3, 48, 61]])

In [69]:
set(arr.flatten()).intersection(set(arr2.flatten()))

{1, 3, 5}

In [72]:
np.intersect1d(arr, arr2)

array([1, 3, 5])

10) Bir matristeki eşsiz (unique) değerleri bulun.

In [73]:
arr3 = np.array([[1, 1, 2],
                 [2, 3, 4]])
arr3

array([[1, 1, 2],
       [2, 3, 4]])

In [74]:
np.unique(arr3)

array([1, 2, 3, 4])

In [76]:
list(set(arr3.flatten()))

[1, 2, 3, 4]

11) `np.all` kullanarak hangi değerlerin `True` & `False` olduğunu belirleyin.

In [80]:
np.all([True, False])

False

In [83]:
np.all([0])

False