In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
arr = np.around(np.random.uniform(size = (10, 3)) * 100, 2)
arr

array([[52.71, 87.95, 81.9 ],
       [79.73, 46.87, 93.85],
       [61.19, 87.22,  4.76],
       [61.53, 31.33, 24.23],
       [54.03, 94.01, 54.51],
       [ 5.37, 56.6 , 23.07],
       [42.75, 34.8 , 49.69],
       [28.01, 69.3 , 30.96],
       [52.17, 52.14, 68.48],
       [69.03, 38.38, 48.62]])

In [3]:
arr.shape

(10, 3)

In [4]:
np.mean(arr, axis=0)

array([50.652, 59.86 , 48.007])

In [6]:
arr[:, 0].mean()

50.652

In [7]:
np.mean(arr, axis=1)

array([74.18666667, 73.48333333, 51.05666667, 39.03      , 67.51666667,
       28.34666667, 42.41333333, 42.75666667, 57.59666667, 52.01      ])

In [8]:
np.array([52.71, 87.95, 81.9 ]).mean()

74.18666666666667

In [9]:
np.sum(arr, axis=0)

array([506.52, 598.6 , 480.07])