In [1]:
import numpy as np

np.__version__

'1.22.4'

In [3]:
arr = (np.random.rand(5, 2) * 100).astype(int)
arr

array([[84,  2],
       [53, 69],
       [29, 49],
       [36, 53],
       [ 3,  3]])

In [5]:
arr % 2 == 0

array([[ True,  True],
       [False, False],
       [False, False],
       [ True, False],
       [False, False]])

In [4]:
arr[arr % 2 == 0]

array([84,  2, 36])

In [7]:
arr[np.where(arr % 2 == 0)]

array([84,  2, 36])

In [11]:
np.where(arr > 50, arr, 0)

array([[84,  0],
       [53, 69],
       [ 0,  0],
       [ 0, 53],
       [ 0,  0]])

In [9]:
arr

array([[84,  2],
       [53, 69],
       [29, 49],
       [36, 53],
       [ 3,  3]])

In [ ]:
# Elimizde float değerler oluyor
# Bunları 1 veya 0'a yuvarlamak gerekiyor.

In [13]:
arr2 = np.random.rand(5, 2)
arr2

array([[0.47740195, 0.25047491],
       [0.79458793, 0.77339514],
       [0.7012157 , 0.96478542],
       [0.83031055, 0.82209822],
       [0.64824826, 0.36713973]])

In [14]:
np.where(arr2 > 0.5, 1, 0)

array([[0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0]])

In [ ]:
np.where()

In [18]:
arr3 = np.random.permutation(np.arange(0, 25, 2))
arr3

array([22, 24,  2,  8,  4, 18, 10, 14,  6, 20, 16,  0, 12])

In [20]:
np.where(arr3 < 10, arr3*2, arr3)

array([22, 24,  4, 16,  8, 18, 10, 14, 12, 20, 16,  0, 12])