In [2]:
import numpy as np

np.__version__

'1.22.4'

12) 9 elemendan oluşan bir array'i `reshape` kullanmadan (3, 3) haline getirin.

In [3]:
arr = np.arange(0, 9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr.shape = (3, 3)

In [6]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

13) (12, 5) shape'inde full `7` sayısından oluşan bir array oluşturun.

In [8]:
arr = np.ones((12, 5)) * 7
arr

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [12]:
np.full((12, 5), fill_value = 7, dtype="f4")

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]], dtype=float32)

14) (3,5) shape'inde bir array oluşturup ortasına bir dimension ekleyin. Yeni boyut (3, 1, 5) olsun.

In [13]:
arr = np.random.rand(3, 5)
arr

array([[0.51054938, 0.14537613, 0.86388366, 0.52853195, 0.53211579],
       [0.2294535 , 0.81071772, 0.02256217, 0.53346129, 0.44951107],
       [0.59910726, 0.55247068, 0.65631663, 0.23069765, 0.02918473]])

In [14]:
arr.shape

(3, 5)

In [16]:
arr = np.expand_dims(arr, axis=1)

In [17]:
arr.shape

(3, 1, 5)

In [18]:
arr

array([[[0.51054938, 0.14537613, 0.86388366, 0.52853195, 0.53211579]],

       [[0.2294535 , 0.81071772, 0.02256217, 0.53346129, 0.44951107]],

       [[0.59910726, 0.55247068, 0.65631663, 0.23069765, 0.02918473]]])

15) Bir önceki soruda yaptığınız fazla dimensionu silin/kaldırın.

In [21]:
np.squeeze(arr, axis=1)

array([[0.51054938, 0.14537613, 0.86388366, 0.52853195, 0.53211579],
       [0.2294535 , 0.81071772, 0.02256217, 0.53346129, 0.44951107],
       [0.59910726, 0.55247068, 0.65631663, 0.23069765, 0.02918473]])

16) (4, 1) shape olan iki array oluşturup sütun bazında concat ederek (4, 1, 2) shape'inde array döndürün.

In [27]:
arr1 = np.expand_dims(np.array([1, 2, 3, 4]), axis=-1)
arr2 = np.array([5, 6, 7, 8])[:, np.newaxis]
arr1

array([[1],
       [2],
       [3],
       [4]])

In [28]:
arr2

array([[5],
       [6],
       [7],
       [8]])

In [29]:
arr2.shape

(4, 1)

In [32]:
arr = np.concatenate([arr1, arr2], axis=1)
arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [33]:
arr = np.expand_dims(arr, axis=1)
arr

array([[[1, 5]],

       [[2, 6]],

       [[3, 7]],

       [[4, 8]]])

In [34]:
arr.shape

(4, 1, 2)

In [36]:
arr = np.dstack((arr1, arr2))

In [38]:
arr[0]

array([[1, 5]])

17) 1'den 9'a kadar olan sayılardan (9 tane item içeren) array oluşturup 3 eşit parçaya bölün.

In [42]:
numbers = np.arange(0, 8)

In [44]:
for _ in range(5):
    print(np.random.choice(numbers))

0
4
3
3
2


In [50]:
arr = np.array([np.random.choice(numbers) for _ in range(9)])
arr

array([0, 5, 3, 6, 4, 3, 4, 0, 1])

In [57]:
np.split(arr, [3, 6])

[array([0, 5, 3]), array([6, 4, 3]), array([4, 0, 1])]

18) 0'dan 25'e kadar sayıları bir matris içine koyup içerisinden:
```python
[[6, 8,
16, 18]]
```
sayılarını bir array olarak çıkarın.

In [60]:
arr = np.arange(0, 25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
arr[1::2, 1::2]

array([[ 6,  8],
       [16, 18]])

In [70]:
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8
