In [1]:
import numpy as np

np.__version__

'1.22.4'

In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) #shape = (2, 3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Tranpose işlemi 2D arraylerde, satır ve sütunların yer
# değiştirmesidir. Neticede shape --> (3, 2) olacaktır (bu durumda)

In [ ]:
# 1 4
# 2 5
# 3 6

In [3]:
arr1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
arr1.shape

(2, 3)

In [8]:
np.transpose(arr1, axes = [1, 0])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# (2, 3) - (2, 3)
# İkinciyi tranpose edersek (2, 3) - (3, 2)
# matmul yapılabilir. Çıktı shape'i (2, 2) matris

In [11]:
arr1 @ arr2.transpose()

array([[14, 32],
       [32, 77]])

In [ ]:
# (224, 224, 3) - 3 channel size RGB olduğunu belirtir.
# np.transpose(array, axes = [2, 0, 1]) --> çıktı shape'i (3, 224, 224)