In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# İlk 3 elemanın indekslenmesi
arr[0:3]

array([1, 2, 3])

In [11]:
# Sondan 1.eleman
arr[-1]

7

In [17]:
arr[-3:]

array([5, 6, 7])

In [19]:
np.shape(arr)

(7,)

In [20]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 2],
    [9, 10, 11],
    [12, 13, 14]
])
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  2],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
arr.shape

(5, 3)

In [27]:
# İlk iki satır ve ilk sütundaki değerler
arr[0:2, 0]

array([0, 3])

In [30]:
# Tüm satırları ve ikinci sütundan sonraki değerler
arr[:, 2:]

array([[ 2],
       [ 5],
       [ 2],
       [11],
       [14]])

In [32]:
# İlk iki sütunu ve tüm satırları içeren indeksleme
arr[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [37]:
# İlk satırdan ikinci satıra kadar olan (ikinci satır dahil) satırlar ve ilk sütundan üçüncü sütuna kadar
arr[:2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
arr[:2, [0, 2]]

array([[0, 2],
       [3, 5]])