In [1]:
import numpy as np

np.__version__

'1.22.4'

| X | Y | Z | Sonuç |
|:---:|:---:|:---:|:---:|
| 4x | -y | z | **2** |
| -x | +y | z | **2** |
| x | 2y | 2z | **3** |

In [2]:
# 4x - y + z = 2
# -x + y + z = 2
# x + 2y + 2z = 3

In [3]:
# Ax = b
# A: katsayılar
# x: bilinmeyenler [x, y, z]
# b: sonuçlar

# (A^-1 A)x = A^-1 b
# A^-1 A --> birim matris (I)
# I x = A^-1 b

In [12]:
np.eye(3) @ x

array([-0.33333333, -0.83333333,  2.5       ])

In [4]:
A = np.array([
    [4, -1, 1],
    [-1, 1, 1],
    [1, 2, 2]
])
# bilinmeyenler = [x, y, z]
b = np.array([2, 2, 3])

In [10]:
np.linalg.det(A)

-6.0

In [9]:
x = np.linalg.inv(A) @ b
x

array([-0.33333333, -0.83333333,  2.5       ])

In [8]:
np.linalg.solve(A, b)

array([-0.33333333, -0.83333333,  2.5       ])

In [16]:
A @ x

array([2., 2., 3.])